name: Elixir CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run generate docs
      run: |
        mix docs -o docs
    - name: push
      uses: github-actions-x/commit@v2.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        rebase: 'true'
        commit-message: 'publish docs'
        force-add: 'false'
        files: docs/
